version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
      - cypress/run:
          install-command: npm i
          store_artifacts: true
          parallel: true
          parallelism: 3
          group: 2 machines