version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: "Test Cart"
          install-command: npm i
          store_artifacts: true
          spec: cypress/e2e/Mod8.cy.js
      - cypress/run:
          name: "Test Login"
          install-command: npm i
          store_artifacts: true
          spec: cypress/e2e/Mod8Login.cy.js